insert into Category (Name) values ('Any Category')
insert into Category (Name) values ('General Knowledge')
insert into Category (Name) values ('Entertainment: Books')
insert into Category (Name) values ('Entertainment: Film')
insert into Category (Name) values ('Entertainment: Music')
insert into Category (Name) values ('Entertainment: Musicals and Theatres')
insert into Category (Name) values ('Entertainment: Television')
insert into Category (Name) values ('Entertainment: Video Games')
insert into Category (Name) values ('Entertainment: Board Games')
insert into Category (Name) values ('Science and Nature')
insert into Category (Name) values ('Science: Computers')
insert into Category (Name) values ('Science: Mathematics')
insert into Category (Name) values ('Mythology')
insert into Category (Name) values ('Sports')
insert into Category (Name) values ('Geography')
insert into Category (Name) values ('History')
insert into Category (Name) values ('Politics')
insert into Category (Name) values ('Art')
insert into Category (Name) values ('Celebrities')
insert into Category (Name) values ('Animals')
insert into Category (Name) values ('Vehicles')
insert into Category (Name) values ('Entertainment: Comics')
insert into Category (Name) values ('Science: Gadgets')
insert into Category (Name) values ('Entertainment: Japanese Anime and Manga')
insert into Category (Name) values ('Entertainment: Cartoon and Animations')